version: "3.8"
services:
  web:
    working_dir: /app
    entrypoint: bash ./entrypoint.sh --prod
    volumes:
      - ./web:/app
    ports:
      - 7007:6655
    env_file:
      - .env.prod
  db:
    volumes:
      - ./data/prod:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 24152:5432
    env_file:
      - .env.prod
  api:
    working_dir: /src
    entrypoint: bash ./entrypoint.sh --prod
    volumes:
      - ./api:/src
    ports:
      - 8866:5000
    env_file:
      - .env.prod
  bot:
    working_dir: /workspace/bot
    entrypoint: bash ./entrypoint.sh --prod
    volumes:
      - ./bot:/workspace/bot
    env_file:
      - .env.prod
